version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  test:
    build:
      context: .
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - .:/app
    depends_on:
      - app
    command: ["poetry", "run", "pytest", "--maxfail=1", "--disable-warnings", "-v"]